#!/bin/sh
if [ $# -gt 0  ]; then
  _words_file="$1"
  if [ ! -e "$_words_file" ]; then
    echo "File doesn't exist: $_words_file" >&2
    exit 1
  fi
  echo "Using words files: $1" 1>&2
  _param="-f $_words_file"
else
  _param="-w"
fi

_bigram_file=~/uniq.10
_unsorted_file=intermediate.pairs.unsorted
_sorted_file=intermediate.pairs
_steps=7

exit_on_error() {
    if [ $1 -ne 0 ]; then
        echo "Exiting, $1" >&2
        exit 1
    fi
}

pair_count() {
    local _lc=$(wc -l "$1" | cut -d' ' -f1)
    echo "  Pairs: $_lc" >&2
}

echo "(1 of $_steps) Generating word pairs..." >&2
if [ ! -z "$_words_file" ]; then
  cm pairs $_param -w > "$_unsorted_file"  # pairs of words_file & words
else
  cm pairs -w > "$_unsorted_file"         # pairs of words
fi
exit_on_error $?

echo "(2 of $_steps) Generating word/solution pairs..." >&2
cm pairs $_param -s >> "$_unsorted_file"  # pairs of words and single-word solution words
exit_on_error $?

echo "(3 of $_steps) Sorting results..." >&2
pair_count "$_unsorted_file"
sort "$_unsorted_file" > "$_sorted_file"

# valid bigrams back to (soon to be) unsorted file
echo "(4 of $_steps) Finding valid bigrams..." >&2
comm -12 "$_bigram_file" "$_sorted_file" > "$_unsorted_file"
exit_on_error $?
pair_count "$_unsorted_file"

echo "(5 of $_steps) Generating word/solutions pairs..." >&2
cm pairs $_param -m >> "$_unsorted_file"  # pairs of words and multiple-word solution words
exit_on_error $?

echo "(6 of $_steps) Generating solutions pairs..." >&2
cm pairs -s -m >> "$_unsorted_file"  # pairs of 1-word and multipe-word solution words
exit_on_error $?

echo "(7 of $_steps) Generating solutions pairs..." >&2
cm pairs -m >> "$_unsorted_file"     # mutliple-word solution words
exit_on_error $?

cat "$_unsorted_file" | sort | uniq

# cleanup
rm "$_unsorted_file"
rm "$_sorted_file"
